### ISSUE TITLE
Google docs erroring with "WebLoginRequired"

### ISSUE THREAD

**Issue by Kirkman** [nprapps/app-template#493]
I've been trying to learn how to use the NPR app template. We are on Windows machines here, so I'm running the template on a FreeBSD server.

When I tried to test `fab text.update`, the the gdocs.py file kept erroring out on line 70. After some poking around, I found that this was being returned by the ClientLogin request:

```
Error=BadAuthentication
Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&plt=[hash snipped]
Info=WebLoginRequired
```

I didn't have a way to do a web login from this machine, since it's a remote server. But eventually I was able to fix it. FWIW, here's what I did:

* Enabling [access to less secure apps](https://www.google.com/settings/security/lesssecureapps) from my local machine
* Clicking "continue" on the [Allow access to your Google account](https://accounts.google.com/DisplayUnlockCaptcha) page from my local machine

Maybe worth adding a check for BadAuthentication errors, and prompt the user to fix it?

**Comment by TylerFisher** [comment]
Pretty sure our new oAuth system gets around this.
