### ISSUE TITLE
App config var for selecting Fontello icons, generating custom build

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/app-template#515]
Var would be the icons you want, script would get fontello build

**Comment by dannydb** [comment]
Related, I generated a fontello package recently with the NPR One player icons, and we could preload those paths with Fontello’s config.json file. Would be great to not have to go pick non-font-awesome player icons per project.

**Comment by eads** [comment]
There is now code in the elections16 repo to make a custom fontello build.

**Comment by TylerFisher** [comment]
Used elections code.
