### ISSUE TITLE
If smartypants fails, print the offending string in the console

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/app-template#522]

**Comment by onyxfish** [comment]
Good idea. Do you have a test case for this?

**Comment by TylerFisher** [comment]
I've fixed it a few times in Liberia. Every time a smart quote was in the place of an apostrophe in the spreadsheet.

**Comment by eads** [comment]
I actually removed the `s.encode('utf-8')` in Syria in the smarty filter to get around this. See https://github.com/nprapps/syria/blob/master/render_utils.py#L209
