### ISSUE TITLE
Sometimes default assets cache headers are a huge pain

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/app-template#524]
Doing last-minute audio edits for Liberia, and those changes aren't reflected on stage unless I rename the file. Maybe have less aggressive headers for staging?

**Comment by onyxfish** [comment]
Hmmm, yeah, this is tricky because on the one hand we want a parallel stack, but on the other hand we want testing to be easy. I think I err toward the latter. Easy configuration change to make.
