### ISSUE TITLE
cssmin breaks calc() by stripping spaces

### ISSUE THREAD

**Issue by dannydb** [nprapps/app-template#540]
Issue is logged in the cssmin project here:

https://github.com/zacharyvoase/cssmin/issues/16

**Comment by dannydb** [comment]
Best solution would probably be to generate the minified version with lessc instead of the python package.

**Comment by dannydb** [comment]
@onyxfish @TylerFisher does this look okay?

https://github.com/nprapps/austin/commit/59043837cbbfa02644098ea239333039408b9892

**Comment by onyxfish** [comment]
Looks great!

**Comment by kristianroebuck** [comment]
If you're using cssmin and want to get around this issue without having to switch to another minifier you're able to change your CSS from this:

`width: calc(100% + 2px);`

to this:

`width: calc(100% - -2px);`

Not ideal, but it works.
