### ISSUE TITLE
Dockerize this template app?

### ISSUE THREAD

**Issue by inadarei** [nprapps/app-template#578]
New year's coming, time for new toys.

This template, if Dockerized, could be used on Windows as well and would avoid version-conflicts/headaches on OS-X (e.g.: would completely remove the need for: http://blog.apps.npr.org/2013/06/06/how-to-setup-a-developers-environment.html).

Interested? Would be happy to land a helping hand.

cheers

**Comment by eads** [comment]
This would be a cool thing. I haven't played with Docker much, so a helping hand would be much appreciated.
